# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pwd
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pwd
      hostname
      echo $BASH_ENV
      echo 'Hello World!!!'
    bashEnvValue: '''ASDFGHJKLLIJNFIBVNFIUNVIUNVUF'''
