# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker run -t gesellix/trufflehog https://github.com/sridharkondeti/DevOpsDemo.git
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mvn clean
      mvn compile
      mvn package
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'scp -o StrictHostKeyChecking=no -i EC2Key.pem -r target/gs-maven-0.1.0 ubuntu@44.197.235.113:/home/ubuntu/apache-tomcat-10.0.27/webapps'
    bashEnvValue: '-----BEGIN RSA PRIVATE KEY----- MIIEpAIBAAKCAQEAjiWsOCqIXdaO1gyJ5Qxk/RgcYSUkF1Tmw0PNK4e3pFXsyVSd Uk2u3b7RHvfgvrOFxrM5rpGx2oXaR142hcAteYNbqYjd4a2eLce3BtRPaUyYq2IA IKWW4iaPfvH2Xa1XaXNYT4xM+Nk+LNHdqpQ5bguIGiy1SsINe2mqHmVVkHLTrHM2 iBAfCQl6IsciAYrjv1E8Xj0u3njmmgjK9mZWU8Rc227PnJQuPBE04TMQZORge/JZ NJ/K3ahDmNhJBagDJGrGSFrKLnXDFSPwfXebCb54GaQJ3/iY67tanJ5kqjhYqDfk OaDfwyyHnAdyjaouGAjst6/EadFcZIqoasJuUQIDAQABAoIBAQCNIdBdL7WXXckR sv9SgDzgoYjD1yl/VNeNdgsGNkjaDEn+F1nf9qsxFRzyX3AwR3QCNb6Gmbd5XL69 b0g5Afbkl8xxhieuwz+y+oC5ciCqTteiCbpQr7ggL+L3Smuu1MVeOJys1oMx7Bf0 TiaFD4f5v89RFaSmZgcWynGSnlAXCrBAJnMx6CF6jxRVvYPIzJAfLx5Be1BHhqLy OsJF8gf86TXueN+7I4wFPF5jmdtDFPML4VDssuqGnyHLy/S/XojkW7tp7lRjpNxt L2eH71WW7TDzFEKT3hZ4tzpeWbKKashWgqO2JnHoLUQbKXiAFv09l24KXFpN6DWI SPrB5EolAoGBAP8YOInDrN91zL5dZYN/iByJp9Kq7aHbwUvK/uUv1fQferltzNw7 jxbbLq6y2aGmqVgw8y99vgVm8at1ETyC9a6DGuGvT0kY1qWMqDuQpYtwckv1L9+r cShE0f15RaAgR9UvN4x+npNdb9ZFNNOYbMIN5cBGqmmfg9SjwcLvjOR7AoGBAI6m 0+bxJ5Za2lFYav8W4gGBQhPA7NEjJ90fJFF4UVdEZNIsONJl15xAfgtCJErw+2cX GSBFpFs0Vdk8mZQEkPV93ZtXv6Vh3PJBfV49WRhoGqbuLPCeWdEWBlvymMVnZzA0 z/lF6IZSyPJpGWJiLaj0rly4TP3Oa4cI+xX+1pyjAoGBAJoCdof+Ik3bYhyAaLxm b7fDCBZxafyxn1byHMgkBElaBA8VknxYXQBQnjOM+UXWSCFdlETU5rd+OmPozto4 url8n+snm3enTlguvpcPslKoNelUA25HpI7KVflxkS6mrpev5Rqmi3ivDclQiR9C xE64c0CNqW8RhlcH8wCM/gQnAoGAcUlPk2IEfEVeh6deIYK8rVFHdoSKDXSL3fEz WHfisRkhsD9qSLyURAR7lNlMFS/Xl4EidRyZb8zaOJEFriUKMctpSEqhaeeUHdeg hkzWCqnyMIuJqPU4gvGozzCT3oFF02S9nUrFZJct+kU44Ybyl/Do372FdzKM9kpN jKQ7L10CgYAXY9b/JksZfeCQM7NBxNFW9Y93OA+ohevHXZSz4FaNyD9ymyHjOALH BWPtRi6fWbGbBO3urdNoSXctesDgCQ4hngwDkwy69mhs6BYvt/8f4hbom5/3an+S bvoO8ZqAHceEMW51wF0XkNbQ17ZaxtDNCo43Y46Cke+394pH1OkY2Q== -----END RSA PRIVATE KEY-----'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker run -t owasp/zap2docker-stable zap-baseline.py -t http://44.197.235.113:8080/gs-maven-0.1.0/hello.jsp  || true'