# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker run -t gesellix/trufflehog https://github.com/sridharkondeti/DevOpsDemo.git
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mvn clean
      mvn compile
      mvn package
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'scp -o StrictHostKeyChecking=no -i EC2Key.pem -r target/gs-maven-0.1.0 ubuntu@44.197.235.113:/home/ubuntu/apache-tomcat-10.0.27/webapps'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker run -t owasp/zap2docker-stable zap-baseline.py -t http://44.197.235.113:8080/gs-maven-0.1.0/hello.jsp  || true'